services:
  # Laravel(PHP-FPM)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/var/www/html
    env_file:
      - ./backend/src/.env
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx (リバースプロキシ)
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend/src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # ホスト8080 → コンテナ80
    depends_on:
      - backend
    networks:
      - app-network

    # Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app
    command: "npm run dev"
    ports:
      - 3000:3000
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    env_file:
      - ./backend/src/.env.mysql
    networks:
      - app-network

volumes:
  mysql-volume:

networks:
  app-network:
    driver: bridge
